FileSharingSystem/Controllers/FileManagementController.cs
using FileSharingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.IO;
using System.Security.Claims;

[Authorize]
public class FileManagementController : Controller
{
    private readonly IFileService _fileService;

    public FileManagementController(IFileService fileService)
    {
        _fileService = fileService;
    }

    public async Task<IActionResult> Index(string searchQuery, string fileType)
    {

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Lấy ID người dùng từ Claims
        var model = await _fileService.GetFilesByUserIdAsync(userId);

        if (model == null)
        {
            model = new List<FileModel>();
        }
        foreach (var file in model)
        {
            file.FileCategory = FileTypeHelper.GetFileCategory(Path.GetExtension(file.FileName));
        }
        // Áp dụng bộ lọc tìm kiếm theo tên tệp nếu có
        if (!string.IsNullOrEmpty(searchQuery))
        {
            model = model.Where(f => f.FileName.Contains(searchQuery, StringComparison.OrdinalIgnoreCase)).ToList();
        }
        // Áp dụng bộ lọc theo loại tệp nếu có
        if (!string.IsNullOrEmpty(fileType))
        {
            model = model.Where(f => f.FileCategory == fileType).ToList();
        }


        return View(model);
    }
    public async Task<IActionResult> UserFiles()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); 
        var model = await _fileService.GetFilesByUserIdAsync(userId);
        return View(model); 
    }

    public async Task<IActionResult> Open(int id)
    {
        try
        {
            var file = await _fileService.GetFileByIdAsync(id);
            if (file == null)
            {
                return NotFound();
            }
            var fileStream = await _fileService.DownloadFileAsync(id);
            var contentType = GetContentType(file.FileName);
            var encodedFileName = Uri.EscapeDataString(file.FileName);
            if (contentType == "application/vnd.openxmlformats-officedocument.wordprocessingml.document" || contentType == "application/msword")
            {
                using (var memoryStream = new MemoryStream())
                {
                    await fileStream.CopyToAsync(memoryStream);
                    memoryStream.Position = 0;

                    var doc = new Aspose.Words.Document(memoryStream);
                    var pdfStream = new MemoryStream();
                    doc.Save(pdfStream, Aspose.Words.SaveFormat.Pdf);
                    pdfStream.Position = 0;

                    Response.Headers.Add("Content-Disposition", $"inline; filename=\"{encodedFileName}\"");
                    return File(pdfStream, "application/pdf");
                }
            }

            Response.Headers.Add("Content-Disposition", $"inline; filename=\"{encodedFileName}\"");
            return File(fileStream, contentType);
        }
        catch (FileNotFoundException)
        {
            return NotFound();
        }
    }


    [HttpPost]
    public async Task<IActionResult> Upload(IFormFile file)
    {
        const long MaxFileSize = 5 * 1024 * 1024; // 5MB
        var allowedExtensions = new[]
        {
        ".jpg", ".jpeg", ".png", ".gif", ".pdf", ".docx", ".doc", ".xls", ".xlsx", ".txt", ".rtf", ".ppt", ".pptx", ".odt", ".ods", ".odp",
        ".mp3", ".wav", ".aac", ".flac", ".ogg", ".wma", ".m4a", ".mp4", ".avi", ".mov", ".mkv", ".flv", ".wmv", ".mpeg", ".3gp",
        ".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz", ".ttf", ".otf", ".woff", ".woff2",
        ".csv", ".ics", ".apk", ".iso", ".exe"
    };

        if (file == null || file.Length == 0)
        {
            TempData["ErrorMessage"] = "Vui lòng chọn tệp để tải lên.";
            return RedirectToAction("Index", "Home");
        }

        if (file.Length > MaxFileSize)
        {
            TempData["ErrorMessage"] = "Kích thước tệp vượt quá giới hạn 5MB.";
            return RedirectToAction("Index", "Home");
        }

        var fileExtension = Path.GetExtension(file.FileName).ToLowerInvariant();
        if (!allowedExtensions.Contains(fileExtension))
        {
            TempData["ErrorMessage"] = "Tệp này không được phép tải lên. Vui lòng chọn tệp có định dạng hợp lệ.";
            return RedirectToAction("Index", "Home");
        }

        try
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var uploadedFile = await _fileService.UploadFileAsync(file, userId);
            TempData["SuccessMessage"] = $"{file.FileName} được xác nhận an toàn. Đã tải lên thành công !";
            TempData["uploadinfo"] = "SAFE" +
                "SCANNER by VIRUSTOTAL";
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = ex.Message; // Lưu thông báo lỗi vào TempData
        }
        return RedirectToAction("Index", "Home");
    }




    public async Task<IActionResult> Download(int id)
    {
        try
        {
            var file = await _fileService.GetFileByIdAsync(id);
            if (file == null)
            {
                return NotFound();
            }
            var fileStream = await _fileService.DownloadFileAsync(id);
            var contentType = GetContentType(file.FileName);

            var encodedFileName = Uri.EscapeDataString(file.FileName);

            Response.Headers.Add("Content-Disposition", $"attachment; filename=\"{encodedFileName}\"");

            return File(fileStream, contentType);
        }
        catch (FileNotFoundException)
        {
            return NotFound();
        }
    }


    public async Task<IActionResult> Delete(int id)
    {
        // Lấy ID người dùng từ Claims
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        // Tìm kiếm tệp dựa trên fileId
        var file = await _fileService.GetFileByIdAsync(id);

        if (file == null)
        {
            return NotFound(); // Trả về 404 nếu không tìm thấy tệp
        }

        // Kiểm tra xem người dùng có quyền xóa tệp không
        if (file.UserId != userId) // Giả định rằng file.UserId lưu ID của người dùng đã tải lên
        {
            TempData["ErrorMessage"] = "Bạn không có quyền xóa tệp này."; // Lưu thông báo vào TempData
            return RedirectToAction("Index"); // Chuyển hướng về trang chính
        }

        await _fileService.DeleteFileAsync(id);
        return RedirectToAction("Index");
    }



    // Hàm xác định Content-Type dựa vào phần mở rộng của tệp
    private string GetContentType(string fileName)
    {
        var provider = new Microsoft.AspNetCore.StaticFiles.FileExtensionContentTypeProvider();
        if (!provider.TryGetContentType(fileName, out var contentType))
        {
            contentType = "application/octet-stream"; // Sử dụng cho các loại tệp không xác định
        }
        return contentType;
    }

}

FileSharingSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileSharingSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileSharingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FileSharingSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileManagement" asp-action="Index">Quản lý file</a>
                        </li>
                       
}
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

            @if (TempData["uploadinfo"] != null)
            {
        <div id="fixedNotification" class="fixed-notification">
            <h2>SAFE</h2>
            <h3>SCANNER BY VIRUSTOTAL</h3>
        </div>
            }

<style>
    /* Định dạng thông báo ghim ở góc trái dưới màn hình */
    .fixed-notification {
        position: fixed;
        bottom: 20px;
        left: 20px;
        background-color: rgba(255, 255, 255, 0.9);
        padding: 10px 20px;
        border: 1px solid #00c853;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
        color: #00c853;
        font-weight: bold;
        text-align: center;
        z-index: 1000;
    }
    .fixed-notification h2 {
        margin: 0;
        font-size: 1.5rem;
    }
    .fixed-notification h3 {
        margin: 0;
        font-size: 1rem;
        color: #555;
    }
</style>

<script>
  
    window.onload = function() {
        const notification = document.getElementById("fixedNotification");
        if (notification) {
            setTimeout(function() {
                notification.style.display = "none";
            }, 10000);
        }
    };
</script>



            &copy; 2024 - FileSharingSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>